### ISSUE TITLE
making oj optional for jruby

### ISSUE THREAD

**Issue by mjobin-mdsol** [JordiPolo/lorekeeper#17]
Hey Jordi,

love your excellent gem 

I was wondering if you would consider making `oj` optional, so that we can use your gem with jruby?

**Comment by JordiPolo** [comment]
The only reason for Oj is that many years ago it would blow out of the water the performance of the json implementation in the standard library, even for small-ish log-like input.

It would be interesting to see new numbers comparing with Ruby 2.7 , the repo has a [performance test](https://github.com/JordiPolo/lorekeeper/blob/master/Rakefile) that could be improved but it is a start. 

Maybe Oj is not even a thing anymore

**Comment by mjobin-mdsol** [comment]
I started adding `oj` here and there from a recommendation from `rollbar`
but I think this should be an application-specific choice. not a gem requirement.
