### ISSUE TITLE
Add Compatibility with Rack::CommonLogger

### ISSUE THREAD

**Issue by abhitrivedi** [JordiPolo/lorekeeper#7]
[Rack::CommonLogger](http://www.rubydoc.info/gems/rack/Rack/CommonLogger) requires the logger class to respond to either `write` or `<<` method.

I was wondering whether we could add one or both of those method so lorekeeper can be used in the middleware stack with Rack::CommonLogger.

Thanks.

**Comment by jcarres-mdsol** [comment]
I totally forgot about this. PR please!

**Comment by miniengineer** [comment]
Here's a long awaited PR 😉 
https://github.com/JordiPolo/lorekeeper/pull/31
